# Generated by Django 2.0.9 on 2019-10-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date tieme when the instance was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time when object was modified', verbose_name='modified_at')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('img', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
