# Generated by Django 2.0.9 on 2019-11-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191018_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='notification_token'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='notification_token'),
        ),
    ]
