# Generated by Django 2.0.9 on 2019-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date tieme when the instance was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time when object was modified', verbose_name='modified_at')),
                ('description', models.SlugField(max_length=225)),
                ('back_team', models.CharField(max_length=20)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('looser', models.CharField(blank=True, max_length=20, null=True)),
                ('draw', models.BooleanField(default=False)),
                ('lay_team', models.CharField(max_length=20)),
                ('is_finished', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date tieme when the instance was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time when object was modified', verbose_name='modified_at')),
                ('back_team', models.CharField(max_length=20)),
                ('opponent', models.CharField(blank=True, max_length=20, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
