# Generated by Django 2.0.9 on 2019-06-10 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='back_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='match',
            name='back_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event'),
        ),
        migrations.AddField(
            model_name='match',
            name='lay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
