# Generated by Django 2.0.9 on 2019-06-18 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0002_auto_20190610_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='direct_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
