# Generated by Django 2.0.9 on 2019-06-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_request_direct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='direct_user',
        ),
    ]
