# Generated by Django 2.0.9 on 2019-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20190707_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='opponent',
            field=models.CharField(max_length=20),
        ),
    ]
