# Generated by Django 2.0.9 on 2019-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20190709_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fq_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sq_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
