# Generated by Django 2.0.9 on 2019-10-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20190710_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
