# Generated by Django 2.0.9 on 2019-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
