# Generated by Django 2.0.9 on 2019-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='img',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sport',
            name='img',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
