# Generated by Django 2.0.9 on 2019-07-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='relation_d_l',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='relation_d_v',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='relation_v_l',
            field=models.SmallIntegerField(null=True),
        ),
    ]
