# Generated by Django 2.0.9 on 2019-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190523_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
