# Generated by Django 2.0.9 on 2019-06-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190614_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='img',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sport',
            name='img',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
