# Generated by Django 2.0.9 on 2019-05-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190523_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='events.Team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_team', to='events.Team'),
        ),
    ]
