# Generated by Django 2.0.9 on 2019-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
