# Generated by Django 2.0.9 on 2019-05-26 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190524_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='users/pictures', verbose_name='league_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='position_draw',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='relation_l_d',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='relation_v_d',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
