# Generated by Django 2.0.9 on 2019-10-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minute',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
