# Generated by Django 2.0.9 on 2019-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190526_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='matched_bets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='position_draw',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='top_bet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='traded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='unmatched_bets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
