# Generated by Django 2.0.9 on 2019-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191021_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='half_time',
            field=models.BooleanField(default=False),
        ),
    ]
