# Generated by Django 2.0.9 on 2019-11-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_half_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='local_tennis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='visit_tennis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
