# Generated by Django 2.0.9 on 2019-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20191106_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
