# Generated by Django 2.0.9 on 2019-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='second_time',
            field=models.BooleanField(default=False),
        ),
    ]
