# Generated by Django 2.0.9 on 2019-11-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_second_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added_time',
            field=models.SmallIntegerField(default=0),
        ),
    ]
